# Generated by Django 2.2.13 on 2020-06-13 18:35

import common.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0002_auto_20200613_1835'),
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('estado', models.CharField(choices=[('A', 'Abierto'), ('C', 'Cerrado')], max_length=1, verbose_name='Estado')),
                ('dia', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sabado'), ('6', 'Domingo')], max_length=1, verbose_name='Día'), size=None)),
            ],
            options={
                'ordering': ('fecha_inicio',),
            },
            bases=(common.models.DiasSemanaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('identificacion', models.CharField(max_length=100, verbose_name='Identificación')),
                ('grupo', models.ForeignKey(help_text='Grupo al que asiste el estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='grupos.Grupo', verbose_name='Grupo')),
                ('miembro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='miembros.Miembro', verbose_name='Líder')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('grupos_minimo', models.IntegerField(default=0, verbose_name='Grupos mínimo')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependecias_set', to='instituto.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('paso', models.NullBooleanField(verbose_name='Pasó')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='instituto.Curso', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='instituto.Estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(verbose_name='Prioridad')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='instituto.Materia', verbose_name='Materia')),
            ],
            options={
                'unique_together': {('materia', 'prioridad')},
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
            ],
            options={
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(verbose_name='Prioridad')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='instituto.Modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name_plural': 'Sesiones',
                'unique_together': {('modulo', 'prioridad')},
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField(verbose_name='Asistencia')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='instituto.Matricula', verbose_name='Matricula')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Sesion', verbose_name='Sesión')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='instituto.Materia', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ManyToManyField(related_name='cursos_como_profesor', to='miembros.Miembro', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='instituto.Salon', verbose_name='Salón'),
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='instituto.Materia')),
            ],
        ),
    ]
