# Generated by Django 2.2.13 on 2020-06-13 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True, verbose_name='cédula')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, verbose_name='segundo nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, verbose_name='segundo apellido')),
                ('jefe_departamento', models.BooleanField(default=False, verbose_name='jefe de departamento')),
                ('cargo', models.CharField(max_length=150, verbose_name='cargo')),
                ('areas', models.ManyToManyField(related_name='empleados', to='organizacional.Area', verbose_name='áreas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'permissions': (('es_administrador_sgd', 'Es Administrador de Sistema Gestion Documental'), ('buscar_registros', 'Puede Buscar Registros'), ('es_compras', 'Es usuario de compras'), ('es_presidente', 'Es presidente')),
            },
        ),
        migrations.AddField(
            model_name='area',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='organizacional.Departamento', verbose_name='departamento'),
        ),
    ]
