# Generated by Django 2.2.13 on 2020-06-13 18:35

import common.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import miembros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Escalafon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('cantidad_grupos', models.IntegerField(verbose_name='cantidad grupos')),
            ],
            options={
                'verbose_name_plural': 'Escalafones',
            },
        ),
        migrations.CreateModel(
            name='TipoMiembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo apellido')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='género')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='celular')),
                ('talla', models.CharField(blank=True, max_length=5, verbose_name='talla')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('cedula', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Se aceptan solo numeros')], verbose_name='cédula')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('profesion', models.CharField(blank=True, max_length=100, null=True, verbose_name='profesion')),
                ('estado_civil', models.CharField(blank=True, choices=[('V', 'Viudo'), ('C', 'Casado'), ('S', 'Soltero'), ('D', 'Divorciado')], max_length=1, null=True, verbose_name='estado civil')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=miembros.models.Miembro.ruta_imagen, verbose_name='foto perfil')),
                ('portada', models.ImageField(blank=True, null=True, upload_to=miembros.models.Miembro.ruta_imagen, verbose_name='portada')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('R', 'Restauración')], max_length=1, verbose_name='estado')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='fecha de registro')),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.Barrio', verbose_name='barrio')),
                ('conyugue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casado_con', to='miembros.Miembro', verbose_name='cónyugue')),
                ('escalafon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lideres', to='miembros.Escalafon', verbose_name='escalafon')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='grupos.Grupo', verbose_name='grupo')),
                ('grupo_lidera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lideres', to='grupos.Grupo', verbose_name='grupo que lidera')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='usuario')),
            ],
            options={
                'permissions': (('es_agente', 'define si un miembro es agente'), ('es_lider', 'indica si el usuario es lider de un GAR'), ('es_administrador', 'es adminisitrador'), ('es_pastor', 'indica si un miembro es pastor'), ('es_tesorero', 'indica si un miembro es tesorero'), ('es_coordinador', 'indica si un miembro es coordinador'), ('es_maestro', 'indica si un miembro es maestro'), ('buscar_todos', 'indica si un usuario puede buscar miembros')),
            },
            bases=(common.models.UtilsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CambioTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anteriorTipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_anterior', to='miembros.TipoMiembro', verbose_name='tipo anterior')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro_autoriza', to='miembros.Miembro')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro_cambiado', to='miembros.Miembro')),
                ('nuevoTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_nuevo', to='miembros.TipoMiembro', verbose_name='tipo nuevo')),
            ],
        ),
        migrations.AddField(
            model_name='barrio',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.Zona'),
        ),
    ]
