# Generated by Django 2.2.13 on 2020-06-13 18:35

import common.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import grupos.models
import grupos.six


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDiscipulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseñanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('GR', 'GRUPO'), ('DI', 'DISCIPULADO')], max_length=2, verbose_name='tipo')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('archivo', models.FileField(upload_to=grupos.models.Enseñanza.ruta_archivo, verbose_name='archivo')),
            ],
            options={
                'permissions': (('can_see_enseñanzas', 'Usuario puede ver enseñanzas'),),
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50, verbose_name='dirección')),
                ('fechaApertura', models.DateField(verbose_name='fecha de apertura')),
                ('diaGAR', models.CharField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sabado'), ('6', 'Domingo')], max_length=1, verbose_name='dia G.A.R')),
                ('horaGAR', models.TimeField(verbose_name='hora G.A.R')),
                ('diaDiscipulado', models.CharField(blank=True, choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sabado'), ('6', 'Domingo')], max_length=1, null=True, verbose_name='dia discipulado')),
                ('horaDiscipulado', models.TimeField(blank=True, null=True, verbose_name='hora discipulado')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'base_manager_name': '_objects',
            },
            bases=(common.models.DiasSemanaMixin, grupos.six.SixALNode, models.Model),
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('estado', models.CharField(choices=[('AC', 'ACTIVO'), ('IN', 'INACTIVO'), ('SU', 'SUSPENDIDO'), ('AR', 'ARCHIVADO')], max_length=2, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Predica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReunionGAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('predica', models.CharField(max_length=100, verbose_name='prédica')),
                ('numeroTotalAsistentes', models.PositiveIntegerField(verbose_name='Número total de asistentes')),
                ('numeroLideresAsistentes', models.PositiveIntegerField(verbose_name='Número de líderes asistentes')),
                ('numeroVisitas', models.PositiveIntegerField(verbose_name='Número de visitas:')),
                ('novedades', models.TextField(blank=True, default='nada', max_length=500, null=True)),
                ('ofrenda', models.DecimalField(decimal_places=2, max_digits=19)),
                ('confirmacionEntregaOfrenda', models.BooleanField(default=False)),
                ('digitada_por_miembro', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_gar', to='grupos.Grupo')),
            ],
            options={
                'permissions': (('puede_confirmar_ofrenda_GAR', 'puede confirmar la entrega de dinero GAR'),),
            },
        ),
        migrations.CreateModel(
            name='ReunionDiscipulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('novedades', models.TextField(max_length=500)),
                ('ofrenda', models.DecimalField(decimal_places=2, max_digits=19)),
                ('confirmacionEntregaOfrenda', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_discipulado', to='grupos.Grupo')),
                ('predica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Predica', verbose_name='prédica')),
            ],
            options={
                'permissions': (('puede_confirmar_ofrenda_discipulado', 'puede confirmar la entrega de dinero discipulado'),),
            },
        ),
    ]
