# Generated by Django 2.2.13 on 2020-06-13 18:35

from django.db import migrations, models
import django.db.models.deletion
import gestion_documental.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'palabra clave',
                'verbose_name_plural': 'palabras claves',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('estante', models.IntegerField(verbose_name='estante')),
                ('caja', models.IntegerField(verbose_name='caja')),
                ('ultima_modificacion', models.DateField(blank=True, null=True, verbose_name='Fecha Última Modificación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='organizacional.Area', verbose_name='área')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacional.Empleado', verbose_name='Modificado Por')),
                ('palabras_claves', models.ManyToManyField(blank=True, related_name='registros', to='gestion_documental.PalabraClave', verbose_name='palabras claves')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('areas', models.ManyToManyField(related_name='tipos_documento', to='organizacional.Area', verbose_name='áreas')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PE', 'PENDIENTE'), ('ED', 'ENTREGADO POR DIGITADOR'), ('DC', 'DEVUELTO POR USUARIO DE CONSULTA')], max_length=2, verbose_name='Estado Solicitud')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Devolución')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.Registro', verbose_name='Registro')),
                ('usuario_autoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones', to='organizacional.Empleado', verbose_name='Autoriza')),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='organizacional.Empleado', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Registro',
                'verbose_name_plural': 'Solicitudes de Registro',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCustodiaDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PE', 'PENDIENTE'), ('RE', 'REALIZADO'), ('PR', 'PROCESO')], default='PE', max_length=2, verbose_name='Estado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacional.Area', verbose_name='Área')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_custodia', to='organizacional.Empleado', verbose_name='Solicitante')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.TipoDocumento', verbose_name='Tipo de Documento')),
                ('usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_custodia_recibidas', to='organizacional.Empleado', verbose_name='Usuario Recibe Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=gestion_documental.models.Documento.ruta_archivo, verbose_name='archivo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_documental.Registro', verbose_name='registro')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_documental.TipoDocumento', verbose_name='tipo de documento')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
    ]
