# Generated by Django 2.2.13 on 2020-06-13 18:35

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('termino_gar', models.CharField(default='GAR', max_length=100, verbose_name='termino GAR')),
                ('termino_visitas', models.CharField(default='visitas', max_length=100, verbose_name='termino visitas')),
            ],
            options={
                'verbose_name': 'iglesia',
                'verbose_name_plural': 'iglesias',
            },
        ),
    ]
